const getSpriteForId = (id) => {
	switch (id) {
		default:
			return null;
		case 0:
			return "big-plant.png";
		case 1:
			return "chair-bottom.png";
		case 2:
			return "chair-top.png";
		case 3:
			return "floor-middle.png";
		case 4:
			return "grass-left.png";
		case 5:
			return "kitchen-right.png";
		case 6:
			return "round-table.png";
		case 7:
			return "wall-left-right.png";
		case 8:
			return "chair-left.png";
		case 9:
			return "chair-right.png";
		case 10:
			return "floor-bottom.png";
		case 11:
			return "floor-right-bottom.png";
		case 12:
			return "grass-left-top.png";
		case 13:
			return "kitchen-stove.png";
		case 14:
			return "small-plant.png";
		case 15:
			return "wall-left-top.png";
		case 16:
			return "floor-left-bottom.png";
		case 17:
			return "floor-left.png";
		case 18:
			return "floor-top.png";
		case 19:
			return "floor-right.png";
		case 20:
			return "grass-right-bottom.png";
		case 21:
			return "lamp-left.png";
		case 22:
			return "square-table.png";
		case 23:
			return "wall-middle.png";
		case 24:
			return "floor-right-top.png";
		case 25:
			return "floor-top.png";
		case 26:
			return "grass-bottom.png";
		case 27:
			return "grass-left-bottom.png";
		case 28:
			return "grass-right.png";
		case 29:
			return "lamp-right.png";
		case 30:
			return "wall-bottom.png";
		case 31:
			return "wall-right-bottom.png";
		case 32:
			return "grass-right-top.png";
		case 33:
			return "grass-top.png";
		case 34:
			return "kitchen-sink.png";
		case 35:
			return "kitchen-left.png";
		case 36:
			return "kitchen-middle.png";
		case 37:
			return "left-round-table.png";
		case 38:
			return "wall-end-bottom.png";
		case 39:
			return "wall-right.png";
		case 40:
			return "table-left.png";
		case 41:
			return "middle-table.png";
		case 42:
			return "piano-bottom.png";
		case 43:
			return "piano-top.png";
		case 44:
			return "right-round-table.png";
		case 45:
			return "table-right.png";
		case 46:
			return "wall-end-left.png";
		case 47:
			return "wall-right-top.png";
		case 48:
			return "wall-end-right.png";
		case 49:
			return "wall-end-top.png";
		case 50:
			return "wall-joint-right.png";
		case 51:
			return "wall-joint-bottom.png";
		case 52:
			return "wall-joint-left.png";
		case 53:
			return "wall-joint-top.png";
		case 54:
			return "wall-left-bottom.png";
		case 55:
			return "wall-top-bottom.png";
	}
};

export default getSpriteForId;
